pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success=CI/CD
      - check-success=Ruby Critic
      - check-success=SCSS Critic
    actions:
      merge:
        method: merge
